"""empty message

Revision ID: 3bd1f752819c
Revises: None
Create Date: 2017-02-08 10:21:19.698347

"""

# revision identifiers, used by Alembic.
revision = '3bd1f752819c'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.Column('portrait', sa.String(length=128), nullable=True),
    sa.Column('nicheng', sa.String(length=128), nullable=True),
    sa.Column('guanzhu', sa.Text(length=128), nullable=True),
    sa.Column('fans', sa.Text(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tweets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('content', sa.String(length=128), nullable=True),
    sa.Column('image', sa.Text(length=1024), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('praise', sa.Integer(), nullable=True),
    sa.Column('transmit', sa.String(length=128), nullable=True),
    sa.Column('transmit_count', sa.Integer(), nullable=True),
    sa.Column('comments_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment', sa.String(length=128), nullable=True),
    sa.Column('created_time', sa.Integer(), nullable=True),
    sa.Column('tweet_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweets.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comments')
    op.drop_table('tweets')
    op.drop_table('users')
    ### end Alembic commands ###
